/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CrowdfundingInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "approveCampaign" | "campaignCount" | "campaigns" | "claimRefund" | "contribute" | "contributions" | "createCampaign" | "getCampaign" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignApproved" | "CampaignCreated" | "ContributionReceived" | "RefundClaimed" | "Withdrawal"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace CampaignApprovedEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignCreatedEvent {
      export type InputTuple = [id: BigNumberish, creator: AddressLike, goal: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, creator: string, goal: bigint, deadline: bigint];
      export interface OutputObject {id: bigint, creator: string, goal: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContributionReceivedEvent {
      export type InputTuple = [id: BigNumberish, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, from: string, amount: bigint];
      export interface OutputObject {id: bigint, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [id: BigNumberish, by: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, by: string, amount: bigint];
      export interface OutputObject {id: bigint, by: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEvent {
      export type InputTuple = [id: BigNumberish, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, to: string, amount: bigint];
      export interface OutputObject {id: bigint, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Crowdfunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): Crowdfunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveCampaign: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean, boolean] & {id: bigint, creator: string, title: string, description: string, goal: bigint, pledged: bigint, deadline: bigint, approved: boolean, withdrawn: boolean }],
      'view'
    >
    

    
    claimRefund: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contribute: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [_title: string, _description: string, _goalWei: BigNumberish, _durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getCampaign: TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean, boolean] & {id: bigint, creator: string, title: string, description: string, goal: bigint, pledged: bigint, deadline: bigint, approved: boolean, withdrawn: boolean }],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveCampaign'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean, boolean] & {id: bigint, creator: string, title: string, description: string, goal: bigint, pledged: bigint, deadline: bigint, approved: boolean, withdrawn: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [_title: string, _description: string, _goalWei: BigNumberish, _durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean, boolean] & {id: bigint, creator: string, title: string, description: string, goal: bigint, pledged: bigint, deadline: bigint, approved: boolean, withdrawn: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignApproved'): TypedContractEvent<CampaignApprovedEvent.InputTuple, CampaignApprovedEvent.OutputTuple, CampaignApprovedEvent.OutputObject>;
getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'ContributionReceived'): TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
getEvent(key: 'Withdrawal'): TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;

    filters: {
      
      'CampaignApproved(uint256)': TypedContractEvent<CampaignApprovedEvent.InputTuple, CampaignApprovedEvent.OutputTuple, CampaignApprovedEvent.OutputObject>;
      CampaignApproved: TypedContractEvent<CampaignApprovedEvent.InputTuple, CampaignApprovedEvent.OutputTuple, CampaignApprovedEvent.OutputObject>;
    

      'CampaignCreated(uint256,address,uint256,uint256)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'ContributionReceived(uint256,address,uint256)': TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
      ContributionReceived: TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
    

      'RefundClaimed(uint256,address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    

      'Withdrawal(uint256,address,uint256)': TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
      Withdrawal: TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
    
    };
  }